/* @flow */
import keyMirror from 'keymirror-nested';

const glue = '/';

export const AUTH = keyMirror({
  SIGN_IN_REQUEST: null,
  SIGN_IN_SUCCESS: null,
  SIGN_IN_ERROR: null,
  REGISTER_REQUEST: null,
  REGISTER_SUCCESS: null,
  REGISTER_ERROR: null,
  UPDATE_AUTH_FIELD: null
}, glue, 'AUTH');

export const ARTICLE = keyMirror({
  LOAD_ARTICLE_REQUEST: null,
  LOAD_ARTICLE_SUCCESS: null,
  LOAD_ARTICLE_ERROR: null,
  UNLOAD_ARTICLE: null,
  ADD_COMMENT_REQUEST: null,
  ADD_COMMENT_SUCCESS: null,
  ADD_COMMENT_ERROR: null,
  REMOVE_COMMENT_REQUEST: null,
  REMOVE_COMMENT_SUCCESS: null,
  REMOVE_COMMENT_ERROR: null,
  CREATE_ARTICLE_REQUEST: null,
  CREATE_ARTICLE_SUCCESS: null,
  CREATE_ARTICLE_ERROR: null,
  EDIT_ARTICLE_REQUEST: null,
  EDIT_ARTICLE_SUCCESS: null,
  EDIT_ARTICLE_ERROR: null,
  TOGGLE_ARTICLE_FAVORITE_STATUS_REQUEST: null,
  TOGGLE_ARTICLE_FAVORITE_STATUS_SUCCESS: null,
  TOGGLE_ARTICLE_FAVORITE_STATUS_ERROR: null,
  REMOVE_ARTICLE_REQUEST: null,
  REMOVE_ARTICLE_SUCCESS: null,
  REMOVE_ARTICLE_ERROR: null
}, glue, 'ARTICLE');

export const FEED = keyMirror({
  LOAD_GLOBAL_FEED_REQUEST: null,
  LOAD_USER_FEED_REQUEST: null,
  LOAD_TAG_FEED_REQUEST: null,
  LOAD_AUTHOR_FEED_REQUEST: null,
  LOAD_AUTHOR_FAVORITES_FEED_REQUEST: null,
  LOAD_FEED_SUCCESS: null,
  LOAD_FEED_ERROR: null
}, glue, 'FEED');

export const EDITOR = keyMirror({
  UPDATE_FIELD: null,
  ADD_TAG: null,
  REMOVE_TAG: null,
  RESET: null,
  SET_EDITING_ARTICLE_REQUEST: null,
  SET_EDITING_ARTICLE_SUCCESS: null,
  SET_EDITING_ARTICLE_ERROR: null
}, glue, 'EDITOR');

export const TAG = keyMirror({
  LOAD_POPULAR_TAGS_REQUEST: null,
  LOAD_POPULAR_TAGS_SUCCESS: null,
  LOAD_POPULAR_TAGS_ERROR: null
}, glue, 'TAG');

export const AUTHOR = keyMirror({
  LOAD_AUTHOR_REQUEST: null,
  LOAD_AUTHOR_SUCCESS: null,
  LOAD_AUTHOR_ERROR: null,
  TOGGLE_AUTHOR_FOLLOW_STATUS_REQUEST: null,
  TOGGLE_AUTHOR_FOLLOW_STATUS_SUCCESS: null,
  TOGGLE_AUTHOR_FOLLOW_STATUS_ERROR: null
}, glue, 'AUTHOR');

export const SETTINGS = keyMirror({
  LOAD_EDITING_USER: null,
  UPDATE_USER_FIELD: null,
  RESET: null
}, glue, 'SETTINGS');

export const USER = keyMirror({
  UPDATE_SETTINGS_REQUEST: null,
  UPDATE_SETTINGS_SUCCESS: null,
  UPDATE_SETTINGS_ERROR: null,
  LOAD_USER_REQUEST: null,
  LOAD_USER_SUCCESS: null,
  LOAD_USER_ERROR: null,
  SET_USER_SIGNED_OUT: null
}, glue, 'USER');
